name: Validate proposals with trestle
on:
  pull_request:
    branches:
      - main
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Don't mess with line endings
      run: |
        git config --global core.autocrlf false

    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ubuntu-latest-proposals
        restore-keys: |
          ubuntu-latest-proposals

    - name: Install trestle
      run: pip install -U compliance-trestle

    - name: Run trestle validate
      run: trestle author docs validate -tn proposals -hv